In [1]:
# Import dependencies
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
# Import the generated dataset
data = pd.read_csv("https://static.bc-edx.com/ai/ail-v-1-0/m18/lms/datasets/student-loans.csv")
data

,payment_history,location_parameter,stem_degree_score,gpa_ranking,alumni_success,study_major_code,time_to_completion,finance_workshop_score,cohort_ranking,total_loan_score,financial_aid_score,credit_ranking
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,0
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,0
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,1
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,0
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,1
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,1
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,0
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,1

In [3]:
#Create the features (X) and target (y) datasets. The target dataset should be defined by the “credit_ranking” column. 
#The remaining columns should define the features dataset.

In [4]:
# Separate the X and y data
X = data.drop(columns="credit_ranking")
y = data["credit_ranking"]

In [5]:
#Split the features and target sets into training and testing datasets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [6]:
# Scaling the X data by using StandardScaler()
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[ 0.35308934,  0.38709284,  0.72800124, ..., -0.26639209,
        -0.50776711, -1.0616042 ],
       [ 0.00479307, -0.54431693,  0.15905076, ...,  0.31516508,
        -0.27726535,  0.06276449],
       [ 2.15262006, -0.88301139,  2.53829822, ..., -0.58947941,
        -0.33489079,  2.40519925],
       ...,
       [-0.57570071, -0.43141878,  0.46938738, ...,  0.12131269,
         0.99049431,  0.06276449],
       [ 2.73311384, -1.16525678,  1.96934774, ..., -1.68797629,
        -0.27726535,  0.15646188],
       [ 0.81748436, -1.22170586,  1.03833786, ..., -0.26639209,
         0.01086184, -0.40572246]])

In [7]:
# Transforming the test dataset based on the fit from the training dataset
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[ 0.52723747,  0.07662291,  0.21077353, ..., -0.46024448,
        -0.56539255,  0.43755405],
       [ 0.41113871,  0.07662291,  1.1417834 , ..., -1.4941239 ,
        -0.27726535, -1.15530159],
       [-1.04009574, -0.77011324, -0.20300864, ...,  0.83210478,
        -0.62301799,  1.56192273],
       ...,
       [-0.8659476 ,  0.92335907, -1.39263237, ...,  0.96133971,
         0.35661448, -0.21832768],
       [ 0.93358312, -0.99590955,  0.57283292, ..., -0.33100956,
         0.93286887,  0.15646188],
       [-1.38839201,  0.13307199, -0.87540466, ...,  1.34904449,
         0.58711623,  0.71864622]])

In [8]:
# Check the max and min of the scaled training and testing sets
print("Scaled data min/max (StandardScaler):")
print("Training data min:",X_train_scaled.min())
print("Training data max:",X_train_scaled.max())
print("Testing data min:",X_test_scaled.min())
print("Testing data max:",X_test_scaled.max())

Scaled data min/max (StandardScaler):
Training data min: -3.6911176491448554
Training data max: 11.050267863326395
Testing data min: -3.5088107205481274
Testing data max: 9.763112599489595